# Autogenerated default.nix for ai
{
  callPackage,
}:
{
  aiac = callPackage ./aiac { };
  aichat = callPackage ./aichat { };
  aide = callPackage ./aide { };
  aider-desk = callPackage ./aider-desk { };
  aiger = callPackage ./aiger { };
  aiken = callPackage ./aiken { };
  aileron = callPackage ./aileron { };
  ain = callPackage ./ain { };
  aiodnsbrute = callPackage ./aiodnsbrute { };
  # ...other packages...
}
